version: '3.8'

services:
  localstack:
    image: localstack/localstack:latest
    container_name: aws-genai-workshop-localstack
    ports:
      - "4566:4566"              # LocalStack Gateway
      - "4510-4559:4510-4559"    # External service ports
    environment:
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LOCALSTACK_HOST=localhost
      - SERVICES=s3,dynamodb,secretsmanager,iam,sts,bedrock,sagemaker,lambda,logs
      - AWS_DEFAULT_REGION=us-east-1
      - PERSISTENCE=1
      - LAMBDA_EXECUTOR=docker
      - LAMBDA_REMOVE_CONTAINERS=false
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./localstack/volume:/var/lib/localstack"
      - "./localstack/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh"
    networks:
      - genai-workshop

  postgres:
    image: postgres:16-alpine
    container_name: aws-genai-workshop-postgres
    environment:
      - POSTGRES_DB=workshop_db
      - POSTGRES_USER=workshop_user
      - POSTGRES_PASSWORD=workshop_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./localstack/sample-data:/docker-entrypoint-initdb.d
    networks:
      - genai-workshop

networks:
  genai-workshop:
    driver: bridge

volumes:
  postgres_data:
