name: RAG Level 1 Validation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  validate-rag:
    runs-on: ubuntu-latest
    name: "Validate RAG Level 1"
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
    
    - name: Install dependencies
      run: |
        uv venv
        uv pip install numpy requests
    
    - name: Run Level 1 RAG validation
      run: |
        uv run python scripts/validate_rag_level1.py --ci
    
    - name: Upload RAG artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: rag-index
        path: rag_cache/
        retention-days: 7
    
    - name: Test with make command
      run: |
        make validate-ci

  validate-multiplatform:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.10', '3.11', '3.12']
    
    runs-on: ${{ matrix.os }}
    name: "Test on ${{ matrix.os }} - Python ${{ matrix.python-version }}"
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies (minimal)
      run: |
        pip install numpy requests
    
    - name: Run validation
      run: |
        python scripts/validate_rag_level1.py --ci --cache-dir ./test-cache-${{ matrix.os }}-${{ matrix.python-version }}
    
    - name: Check results
      run: |
        ls -la test-cache-*/